Fix indentation: Move _save_player_profile_sync into Database class
The _save_player_profile_sync method was defined at module level instead of
being properly indented as a Database class method. This caused AttributeError:
'Database' object has no attribute 'save_player_profile'.

Fixed by indenting the method definition and body by 4 spaces to be part of
the Database class.